create selected data table
NPLinker/nplinker-webapp pull request #30
Opened 2024-08-14 14:57 UTC by gcroci2

2024-08-20 13:30 UTC, CunliangGeng requested changes
Nice changes!  Before reviewing the details of the code, I have some suggestions (see figure below):
1. Add `OR` label to each filter?
2. Change the button `Select/Deselect all` to a selection box?

![image](https://github.com/user-attachments/assets/fbe77dbb-4f8d-4a55-9591-4fb124bf1178)

2024-08-28 08:20 UTC, gcroci2 commented
> 1. Add `OR` label to each filter?

> 2. Change the button `Select/Deselect all` to a selection box?
Done. I first tried to directly edit the first column name of the DataTable, but that was not doable since the "selection" column is not an easily accessible one (it's created by setting `row_selectable="multi"` in the DataTable component, so we don't have direct access to it for editing), and on top of this columns headers seem to require strings, and do not accept other Dash components. So I ended up tweaking the `dcc.Checklist` component style to move it in the place you suggested.

2024-09-09 09:02 UTC, CunliangGeng reviewed
Nice changes, I like it.

It looks the filter of `BGC class` does not work properly. For GCFs that do not have a BGC class should have a label `Unknown`, but if you check your test data `mock_obj_data.pkl`, `Unknown` gives nothing. Or you can try selecting all labels in `BGC class`, which does not give all data available.

2024-09-09 12:26 UTC, gcroci2 commented on requirements.txt
> +python-dotenv
I removed it, I think I left it by mistake

2024-09-09 12:55 UTC, gcroci2 commented
> Nice changes, I like it.
> 
> It looks the filter of `BGC class` does not work properly. For GCFs that do not have a BGC class should have a label `Unknown`, but if you check your test data `mock_obj_data.pkl`, `Unknown` gives nothing. Or you can try selecting all labels in `BGC class`, which does not give all data available.

The issue is fixed now—thanks for pointing it out, @CunliangGeng! It was caused by a mix-up between capitalized and non-capitalized class names.

2024-09-10 08:57 UTC, CunliangGeng approved these changes
It works! :shipit: 

One thought about plotting: currently we provide one plot for `#BGC -> #GCF`, users may also want other plots such as `BGC class -> #GCF`. 
I'm thinking, instead of providing one or two plots beforehand, we leave it for users to do it: 
- we provide the options for x and y, e.g. #GCF, #BGC, BGC class, for users to choose
- we provide different plot styles for users to choose, e.g. histogram, box plot
- users choose those and click plot, then get whatever plots they want
We don't have to implement it now, and could ask for feedbacks on this idea on the community meeting.

2024-09-11 14:49 UTC, gcroci2 commented
We have now some nice ideas to further improve the plot functionality. Which ones to we want to pick up in the current PR? @CunliangGeng 

To recap, the following are the "mandatory" todos:
- Add the hyperlinks to the table's elements (see https://github.com/NPLinker/nplinker-webapp/issues/21)
- Fix the filtering/selection bug I mentioned above

And the following are nice additions to decide priority on:
- Add options for x and y axis, e.g. #GCF, #BGC, BGC class, for users to choose
- Provide different plot styles for users to choose, e.g. histogram, box plot
- Add BGC ID and strain filters

I will then open new issues, if needed, accordingly.

2024-09-12 07:05 UTC, CunliangGeng commented
Thanks for the recap @gcroci2. It's good to merge the current PR and open new ones for the rest issues.

As for the priority, I think it's better to finish the whole page before adding new features like custom plot:

- Add BGC ID and strain filters

- add scoring part 

- custom plot
  - Add options for x and y axis, e.g. #GCF, #BGC, BGC class, for users to choose
  - Provide different plot styles for users to choose, e.g. histogram, box plot


What do you think?

2024-09-13 14:30 UTC, gcroci2 commented
> What do you think?

I created a new view for the webapp, see [here](https://github.com/orgs/NPLinker/projects/9/views/11). I labeled there as a priority the issues for finishing the genomics -> metabolomics tab. Then the other issues in "Todo" can be picked up, and the ones with "ehnancement" label (such as the plotting customization) will be the latter to be picked up. 

So next week I will wrap up this PR, in particular by adding the hyperlinks to the table's elements (with at least some basic info displayed), and by fixing the filtering/selection bug I mentioned above.

2024-09-19 14:41 UTC, gcroci2 commented
We decided to add a filter button to display the filtered data on the DataTable instead of allowing the user to go back and forth between the filter and the DataTable.

2024-09-19 14:41 UTC, closed without merging

2024-09-23 14:25 UTC, gcroci2 commented
Almost done! @CunliangGeng 
- I resolved the issue with filtering and row selection by adding a button to apply the filters. Each time the button is clicked, the DataTable row selection is reset. The select-all checkbox functionality is also improved for better consistency.
- I implemented tooltips using the DataTable’s `tooltip_data` feature. For now, I’ve arbitrarily set the GCF's `strains` attribute to display in the GCF IDs column and the BGCs' `id` attribute in the "# BGC" column. Let me know if we want to display additional information or if I should open an issue for future enhancements.
   - Initially, I explored using `dbc.Tooltip` for greater flexibility. However, dynamically adding a tooltip to each row/column element would require individual element IDs to be passed to the "target" parameter of `dbc.Tooltip`. After some investigation, I couldn’t find a straightforward way to achieve this, and it seems that `DataTable` doesn't support such dynamic elements (without embedding some Javascript on the client side).
   - Should I invest more time exploring the `dbc.Tooltip` option, or should I open a future issue for this enhancement? The key advantage of `dbc.Tooltip` is its flexibility, allowing us to embed complex content and enable user interaction, features not supported by the built-in DataTable tooltips.

2024-09-24 08:34 UTC, CunliangGeng reviewed
Looks good to me!

We could keep the current tooltips, but it's better to 
1. display the text in a table format for strain IDs and BGC IDs (a one column table, later we can add more columns)?
2. the tooltips can be displayed  but will disappear when I try to select and copy text from it. Is there a way to do that?

2024-09-24 14:22 UTC, gcroci2 commented
> 1. display the text in a table format for strain IDs and BGC IDs (a one column table, later we can add more columns)?

I did it using a markdown type of text, since the `tooltip_data` parameter supports only plain text and markdown-formatted text. 

> 2. the tooltips can be displayed  but will disappear when I try to select and copy text from it. Is there a way to do that?

I am aware of this issue, but I did't find anything to handle it using such tooltips. 

Both 1. and 2. kind of enhancements were among the reasons why I wanted to use a `dbc.Tooltip` rather than the ones built-in DataTables, which have much more simpler functionalities and so are quite limited. But `dbc.Tooltip` have not been designed to be incorporated in DataTable rows' elements.

2024-09-25 08:25 UTC, CunliangGeng commented
> I did it using a markdown type of text, since the tooltip_data parameter supports only plain text and markdown-formatted text.

Cool!

Could you change the font or the background to make the tooltip box more visible/highlighted? Maybe make the font smaller or using a colourful background?

For the column Strains, better to directly display the strain names (ordered) instead of a StrainCollection.
For the BCG table, also better to make the column ordered by e.g. alphabet.
 
>I am aware of this issue, but I did't find anything to handle it using such tooltips.
OK, let's record it as an issue and improve it later.

2024-09-27 15:20 UTC, gcroci2 commented
> Could you change the font or the background to make the tooltip box more visible/highlighted? Maybe make the font smaller or using a colourful background?

> For the column Strains, better to directly display the strain names (ordered) instead of a StrainCollection.
For the BCG table, also better to make the column ordered by e.g. alphabet.

Done :)

> OK, let's record it as an issue and improve it later.

Opened in #35

2024-10-01 08:59 UTC, CunliangGeng reviewed
I like the new style of tooltip. There is one more issue: 

When the data table has multiple pages, the display position of tooltip for the page 2+ will be kind of random... 
![image](https://github.com/user-attachments/assets/3f46f030-27c7-49d7-b628-a52addde5589)